# Generated by Django 5.1.4 on 2024-12-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVYONIK', 'Aviyonik')], max_length=50)),
                ('aircraft_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KANAT_TAKIMI', 'Kanat Takımı'), ('GOVDE_TAKIMI', 'Gövde Takımı'), ('KUYRUK_TAKIMI', 'Kuyruk Takımı'), ('AVYONIK_TAKIMI', 'Aviyonik Takımı'), ('MONTAJ_TAKIMI', 'Montaj Takımı')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assembled', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(to='core.part')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
