# Generated by Django 5.1.4 on 2024-12-06 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='assembled',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='part',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], default='AKINCI', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='production_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-15 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='target_aircraft_type',
            field=models.CharField(blank=True, choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], help_text='Hangi uçak tipi için üretildi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='used',
            field=models.BooleanField(default=False, help_text='Parça bir uçakta kullanıldı mı?'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], default='kanat', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='core.aircraft'),
        ),
        migrations.AddField(
            model_name='part',
            name='production_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-15 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='kuyruk_personeli', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('KANAT_TAKIMI', 'Kanat Takımı'), ('GOVDE_TAKIMI', 'Gövde Takımı'), ('KUYRUK_TAKIMI', 'Kuyruk Takımı'), ('AVIYONIK_TAKIMI', 'Aviyonik Takımı'), ('MONTAJ_TAKIMI', 'Montaj Takımı')], default='kuyruk_takimi', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
