# Generated by Django 5.1.4 on 2024-12-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='produced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_aircrafts', to='core.team'),
        ),
    ]
